-- MySQL Script generated by MySQL Workbench
-- Tue Aug 26 14:20:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_capstone_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_capstone_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_capstone_project` DEFAULT CHARACTER SET utf8 ;
USE `db_capstone_project` ;

-- -----------------------------------------------------
-- Table `db_capstone_project`.`MenuItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_capstone_project`.`MenuItems` ;

CREATE TABLE IF NOT EXISTS `db_capstone_project`.`MenuItems` (
  `MenuItemsID` INT NOT NULL AUTO_INCREMENT,
  `CourseName` VARCHAR(45) NULL,
  `StarterName` VARCHAR(45) NULL,
  `DesertName` VARCHAR(45) NULL,
  `DrinkName` VARCHAR(45) NULL,
  `SideName` VARCHAR(45) NULL,
  PRIMARY KEY (`MenuItemsID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_capstone_project`.`Menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_capstone_project`.`Menus` ;

CREATE TABLE IF NOT EXISTS `db_capstone_project`.`Menus` (
  `MenuID` INT NOT NULL AUTO_INCREMENT,
  `MenuItemsID` INT NOT NULL,
  `MenuName` VARCHAR(45) NULL,
  `Cuisine` VARCHAR(45) NULL,
  PRIMARY KEY (`MenuID`),
  INDEX `MenuItemsID_idx` (`MenuItemsID` ASC) VISIBLE,
  CONSTRAINT `MenuItemsID`
    FOREIGN KEY (`MenuItemsID`)
    REFERENCES `db_capstone_project`.`MenuItems` (`MenuItemsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_capstone_project`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_capstone_project`.`Staff` ;

CREATE TABLE IF NOT EXISTS `db_capstone_project`.`Staff` (
  `StaffID` INT NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(45) NOT NULL,
  `JobTittle` VARCHAR(45) NULL,
  `HireDate` DATETIME NULL,
  `Salary` DECIMAL(12,2) NULL,
  `ContactNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`StaffID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_capstone_project`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_capstone_project`.`Customers` ;

CREATE TABLE IF NOT EXISTS `db_capstone_project`.`Customers` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(45) NULL,
  `ContactNumber` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_capstone_project`.`Booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_capstone_project`.`Booking` ;

CREATE TABLE IF NOT EXISTS `db_capstone_project`.`Booking` (
  `BookingID` INT NOT NULL AUTO_INCREMENT,
  `BookingDate` DATETIME NULL,
  `TableNo` INT NULL,
  `CustomerID` INT NOT NULL,
  PRIMARY KEY (`BookingID`),
  INDEX `CustomerID_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `CustomerID`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `db_capstone_project`.`Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_capstone_project`.`OrderStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_capstone_project`.`OrderStatus` ;

CREATE TABLE IF NOT EXISTS `db_capstone_project`.`OrderStatus` (
  `StatusID` INT NOT NULL AUTO_INCREMENT,
  `StatusName` VARCHAR(45) NULL,
  `DeliveryDate` DATETIME NULL,
  `Note` VARCHAR(45) NULL,
  PRIMARY KEY (`StatusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_capstone_project`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_capstone_project`.`Order` ;

CREATE TABLE IF NOT EXISTS `db_capstone_project`.`Order` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `OrderDate` DATETIME NULL,
  `TotalCost` DECIMAL(12,2) NOT NULL,
  `StaffID` INT NULL,
  `BookingID` INT NULL,
  `StatusID` INT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `StaffID_idx` (`StaffID` ASC) VISIBLE,
  INDEX `BookingID_idx` (`BookingID` ASC) VISIBLE,
  INDEX `StatusID_idx` (`StatusID` ASC) VISIBLE,
  CONSTRAINT `StaffID`
    FOREIGN KEY (`StaffID`)
    REFERENCES `db_capstone_project`.`Staff` (`StaffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BookingID`
    FOREIGN KEY (`BookingID`)
    REFERENCES `db_capstone_project`.`Booking` (`BookingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StatusID`
    FOREIGN KEY (`StatusID`)
    REFERENCES `db_capstone_project`.`OrderStatus` (`StatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_capstone_project`.`OrderDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_capstone_project`.`OrderDetail` ;

CREATE TABLE IF NOT EXISTS `db_capstone_project`.`OrderDetail` (
  `MenuID` INT NOT NULL,
  `OrderID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  INDEX `OrderID_idx` (`OrderID` ASC) VISIBLE,
  INDEX `MenuID_idx` (`MenuID` ASC) VISIBLE,
  CONSTRAINT `MenuID`
    FOREIGN KEY (`MenuID`)
    REFERENCES `db_capstone_project`.`Menus` (`MenuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OrderID`
    FOREIGN KEY (`OrderID`)
    REFERENCES `db_capstone_project`.`Order` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
